[project]
name = "velvet-lang"
version = "0.1.0"
dependencies = [
    "rich>=13.9.2",
    "watchdog>=4.0.0",  # For hot reload
    "ruamel.yaml>=0.18.0",  # YAML serialization
    "toml>=0.10.2",  # TOML
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
