[package]
name = "weave"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }  # CLI parsing
crossterm = "0.28.1"  # Cyberpunk terminal UI
walkdir = "2.5.0"  # Directory traversal
